version: "3.8"

services:
  form-checker-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: form-checker-app
    depends_on:
      - form-checker-mongodb
    ports:
      - 8000:8000
    networks:
      - app-network

  form-checker-mongodb:
    image: mongo:6.0
    container_name: form-checker-mongodb
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_DATABASE_NAME}
    ports:
      - 27017:27017
    networks:
      - app-network

  mongo-express:
    image: mongo-express:1.0.2
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_ROOT_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_ROOT_PASSWORD}
      - ME_CONFIG_MONGODB_URL=mongodb://${MONGO_ROOT_USERNAME}:${MONGO_ROOT_PASSWORD}@form-checker-mongodb:${MONGO_PORT}/
      - ME_CONFIG_BASICAUTH=false
    depends_on:
      - form-checker-mongodb
    networks:
      - app-network

networks:
  app-network:
